[build]
  publish = "2025"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/guestbook"
  status = 200